### ISSUE TITLE
airplay pairing fail

### ISSUE THREAD

**Issue by crissmil** [sebbo2002/node-pyatv#208]
Pairing with companion is working, however pairing with airplay gives below error. 
atvremote version 0.10.3
without airplay credentials I cannot subscribe to live events. 
Is this a known issue?

=================================

       Name: AppleTV
   Model/SW: Apple TV 4K, tvOS 16.3
    Address: x.x.x.x
        MAC: xx:xx:xx:xx:xx:xx
 Deep Sleep: False
Identifiers:
 - xx:xx:xx:xx:xx:xx
 - xxxxxxxxxxxx
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled

=============================

pi@raspberrypi:~ $ atvremote --id xx:xx:xx:xx:xx:xx --protocol airplay pair
2023-02-01 21:21:50 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/airplay/auth/hap.py", line 43, in start_pairing
    await self.http.post("/pair-pin-start", headers=_AIRPLAY_HEADERS)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/http.py", line 361, in post
    "POST", path, headers=headers, body=body, allow_error=allow_error
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/http.py", line 417, in send_and_receive
    response.code,
pyatv.exceptions.HttpError: HTTP/1.1 method POST failed with code 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 179, in pair
    await self._perform_pairing(pairing)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 189, in _perform_pairing
    await pairing.begin()
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/airplay/pairing.py", line 63, in begin
    self.pairing_procedure.start_pairing, exceptions.PairingError
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/__init__.py", line 41, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: HTTP/1.1 method POST failed with code 400: Bad Request

**Comment by sebbo2002** [comment]
@crissmil Since you have a problem with atvremote or pyatv directly, you should look for help [there](https://github.com/postlund/pyatv/issues). I can only offer help here for problems concerning my code (node-pyatv) itself, but not for third-party code like pyatv or it's atvremote tool.
