### ISSUE TITLE
Python 3.11 and 3.12 incompatability

### ISSUE THREAD

**Issue by maxileith** [sebbo2002/node-pyatv#270]
Hello there,

I am currently developing a homebridge plugin and utilizing you awesome wrapper.

The only problem is, that once I use a python version higher than 3.10, the following error occurs:

```
Error: Got pyatv Error: Passing coroutines is forbidden, use tasks explicitly.

pyatv Stacktrace:
Traceback (most recent call last):
  File "/home/maxileith/Downloads/homebridge-appletv/dist/.venv/lib/python3.11/site-packages/pyatv/scripts/atvscript.py", line 389, in appstart
    args.output(await _handle_command(args, abort_sem, storage, loop)),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv/dist/.venv/lib/python3.11/site-packages/pyatv/scripts/atvscript.py", line 271, in _handle_command
    return await _run_command(atv, args, abort_sem, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxileith/Downloads/homebridge-appletv/dist/.venv/lib/python3.11/site-packages/pyatv/scripts/atvscript.py", line 305, in _run_command
    await wait_for_input(loop, abort_sem)
  File "/home/maxileith/Downloads/homebridge-appletv/dist/.venv/lib/python3.11/site-packages/pyatv/scripts/atvscript.py", line 167, in wait_for_input
    await asyncio.wait(
  File "/home/maxileith/.pyenv/versions/3.11.6/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

    at parseState (/home/maxileith/Downloads/homebridge-appletv/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:267:15)
    at A.applyPushUpdate (/home/maxileith/Downloads/homebridge-appletv/node_modules/@sebbo2002/node-pyatv/src/lib/device-events.ts:94:30)
    at A.parsePushUpdate (/home/maxileith/Downloads/homebridge-appletv/node_modules/@sebbo2002/node-pyatv/src/lib/device-events.ts:84:14)
    at /home/maxileith/Downloads/homebridge-appletv/node_modules/@sebbo2002/node-pyatv/src/lib/device-events.ts:159:36
    at Array.forEach (<anonymous>)
    at Socket.p (/home/maxileith/Downloads/homebridge-appletv/node_modules/@sebbo2002/node-pyatv/src/lib/device-events.ts:159:18)
    at Socket.emit (node:events:529:35)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Socket.Readable.push (node:internal/streams/readable:245:10)
```

**Comment by sebbo2002** [comment]
What does your code look like exactly? Maybe you can post a code example or a Docker container that I can use to reproduce the error? Are there log messages when you set `debug`?

**Comment by maxileith** [comment]
Thank you for the quick response. I will give you an Update tomorrow and try to create some code that reproduces the error.

**Comment by sebbo2002** [comment]
Yes, that would be very good. From your description and the stacktrace I would currently assume that this is not a problem with `node-pyatv` but with `pyatv` itself. When you create a listener in `node-pyatv`, `atvscript [...] push_updates` is executed in the background. Does this work for you when you run it manually in your environment?

**Comment by maxileith** [comment]
I just tried to run the `atvscript` with the push_updates argument with 3.10. No problem as I expected. With 3.11 however, the error from above appears, so it seems like it is not an issue with your library.

```
atvscript -s 192.168.0.15 push_updates --companion-credentials xxxxx --airplay-credentials xxxxx
{"result": "success", "datetime": "2023-10-25T16:41:21.608656+02:00", "power_state": "on"}
{"result": "success", "datetime": "2023-10-25T16:41:21.608717+02:00", "output_devices": [{"name": "Wohnzimmer (2)", "identifier": "82091D04-8D8E-4CF8-8FAA-4B7FC9979EB9"}]}
{"result": "success", "datetime": "2023-10-25T16:41:21.609241+02:00", "hash": "ca496c14642c78af6dd4250191fe175f6dafd72b4c33bcbab43c454aae051da1", "media_type": "unknown", "device_state": "idle", "title": null, "artist": null, "album": null, "genre": null, "total_time": null, "position": null, "shuffle": "off", "repeat": "off", "series_name": null, "season_number": null, "episode_number": null, "content_identifier": null, "app": null, "app_id": null}
{"result": "failure", "datetime": "2023-10-25T16:41:21.609453+02:00", "exception": "Passing coroutines is forbidden, use tasks explicitly.", "stacktrace": "Traceback (most recent call last):\n  File \"/home/maxileith/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pyatv/scripts/atvscript.py\", line 389, in appstart\n    args.output(await _handle_command(args, abort_sem, storage, loop)),\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/maxileith/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pyatv/scripts/atvscript.py\", line 271, in _handle_command\n    return await _run_command(atv, args, abort_sem, loop)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/maxileith/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pyatv/scripts/atvscript.py\", line 305, in _run_command\n    await wait_for_input(loop, abort_sem)\n  File \"/home/maxileith/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pyatv/scripts/atvscript.py\", line 167, in wait_for_input\n    await asyncio.wait(\n  File \"/home/maxileith/.pyenv/versions/3.11.6/lib/python3.11/asyncio/tasks.py\", line 425, in wait\n    raise TypeError(\"Passing coroutines is forbidden, use tasks explicitly.\")\nTypeError: Passing coroutines is forbidden, use tasks explicitly.\n"}
/home/maxileith/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pyatv/scripts/atvscript.py:393: RuntimeWarning: coroutine 'Semaphore.acquire' was never awaited
  print(args.output(output(False, exception=ex)), flush=True)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/maxileith/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pyatv/scripts/atvscript.py:393: RuntimeWarning: coroutine 'StreamReader.readline' was never awaited
  print(args.output(output(False, exception=ex)), flush=True)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

To make things even more weird, the `atvremote push_updates` works like a charm:

```
atvremote -s 192.168.0.15 push_updates --companion-credentials xxxxx --airplay-credentials xxxxx
Press ENTER to stop
  Media type: Unknown
Device state: Idle
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Paused
       Title: Der Diktator
    Position: 4411/5054s (87.3%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: Der Diktator
    Position: 4411/5054s (87.3%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: Der Diktator
    Position: 4412/5054s (87.3%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Paused
       Title: Der Diktator
    Position: 4411/5054s (87.3%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Paused
       Title: Der Diktator
    Position: 4417/5054s (87.4%)
      Repeat: Off
     Shuffle: Off
--------------------
```

**Comment by maxileith** [comment]
I have opened an issue at the pyatv repo: https://github.com/postlund/pyatv/issues/2268
