### ISSUE TITLE
Node findet AppleTV aber gibt Error 

### ISSUE THREAD

**Issue by schneidy76** [sebbo2002/node-pyatv#343]
Ich konnte mich mit dem AppleTV verbinden, aber der Node gibt folgenden Error raus:

```
Error: Got pyatv Error: Odd-length string

pyatv Stacktrace:
Traceback (most recent call last):
  File "/home/pi/pyatv_venv/lib/python3.11/site-packages/pyatv/scripts/atvscript.py", line 395, in appstart
    args.output(await _handle_command(args, abort_sem, storage, loop)),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pyatv_venv/lib/python3.11/site-packages/pyatv/scripts/atvscript.py", line 273, in _handle_command
    atv = await connect(config, loop, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pyatv_venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/home/pi/pyatv_venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 723, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pyatv_venv/lib/python3.11/site-packages/pyatv/protocols/companion/__init__.py", line 644, in _connect
    await api.connect()
  File "/home/pi/pyatv_venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 151, in connect
    await self._protocol.start()
  File "/home/pi/pyatv_venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 103, in start
    self.srp.pairing_id = parse_credentials(self.service.credentials).client_id
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pyatv_venv/lib/python3.11/site-packages/pyatv/auth/hap_pairing.py", line 141, in parse_credentials
    ltpk = binascii.unhexlify(split[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Odd-length string
```

ich kann leider nichts damit anfangen....

**Comment by sebbo2002** [comment]
Das ist auf jeden Fall ein Fehler aus pyatv, nicht direkt aus node-pyatv. Wie schaut denn dein Code dazu aus? Setze mal `debug: true` bei diesem Befehl, um herauszufinden, was da das ausgeführte Kommando ist. Und damit müsstest du dann vermutlich ein Ticket direkt bei https://github.com/postlund/pyatv aufmachen, mit pyatv Fehlern kann ich leider nicht weiter helfen.
